platform :osx, '10.7'

target 'AdvanceKextUpdater' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AdvanceKextUpdater
  pod 'STPrivilegedTask', '~> 1.0.1'
end
